import { useEffect, useState } from 'react';
import { api, formatDateTime } from '../../../services/api';

export function PeoplePage(){
  const [profiles,setProfiles]=useState([]),[teams,setTeams]=useState([]),[customers,setCustomers]=useState([]),[delegations,setDelegations]=useState([]);
  const [mode,setMode]=useState('profile'),[id,setId]=useState(''),[form,setForm]=useState({role:'REP',approverRole:'MANAGER',active:true});
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  async function load(){try{const [p,t,c,d]=await Promise.all([api.get('/admin/profiles?pageSize=100'),api.get('/admin/teams'),api.get('/customers?pageSize=100'),api.get('/admin/delegations')]);setProfiles(p.items);setTeams(t);setCustomers(c.items);setDelegations(d);}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[]);
  function update(key,value){setForm(f=>({...f,[key]:value}));}
  async function save(e){e.preventDefault();setBusy(true);setError('');try{
    if(mode==='team')await api.post('/admin/teams',{name:form.name});
    else if(mode==='delegation')await api.post('/admin/delegations',{approverRole:form.approverRole,teamId:form.teamId||null,delegateProfileId:form.delegateProfileId,validFrom:new Date(form.validFrom).toISOString(),validUntil:new Date(form.validUntil).toISOString(),reason:form.reason});
    else{const body={email:form.email,fullName:form.fullName,role:form.role,teamId:form.teamId||null,customerId:form.role==='CUSTOMER'?form.customerId:null,active:form.active};if(id)await api.patch(`/admin/profiles/${id}`,body);else await api.post('/admin/profiles',body);}
    setNotice('Configuration saved. Permissions are checked against stored profiles on each request.');await load();
  }catch(e){setError(e.message);}finally{setBusy(false);}}
  const select=(key,label,choices,required=false)=><label>{label}<select required={required} value={form[key]||''} onChange={e=>update(key,e.target.value)}><option value="">Select…</option>{choices.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>;
  return <div className="workspace-page"><div className="workspace-page-header"><div><span className="eyebrow">ACCESS & RESPONSIBILITY</span><h1>People & teams</h1><p>Pre-provision identities and assign qualified approval delegates.</p></div></div>
    <form className="workspace-form insight-panel" onSubmit={save}><label>Configuration<select value={mode} onChange={e=>{setMode(e.target.value);setId('');setForm({role:'REP',approverRole:'MANAGER',active:true});setNotice('');}}><option value="profile">Profile</option><option value="team">Team</option><option value="delegation">Approval delegation</option></select></label>
    {mode==='profile'&&<><label>Profile<select value={id} onChange={e=>{setId(e.target.value);setForm(profiles.find(p=>p.id===e.target.value)||{role:'REP',active:true});}}><option value="">Provision new profile</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.fullName} · {p.email}</option>)}</select></label><div className="grid sm:grid-cols-2 gap-4"><label>Full name<input required value={form.fullName||''} onChange={e=>update('fullName',e.target.value)}/></label><label>Email<input type="email" required disabled={!!id} value={form.email||''} onChange={e=>update('email',e.target.value)}/></label>{select('role','Role',['REP','MANAGER','FINANCE','ADMIN','CUSTOMER'].map(r=>({id:r,name:r})),true)}{select('teamId','Team',teams)}{form.role==='CUSTOMER'&&select('customerId','Customer account',customers,true)}{id&&<label>Active<input type="checkbox" checked={!!form.active} onChange={e=>update('active',e.target.checked)}/></label>}</div><p className="panel-caption">Provisioning assigns access for the matching email; it does not send an invitation or create a password.</p></>}
    {mode==='team'&&<label>Team name<input required value={form.name||''} onChange={e=>update('name',e.target.value)}/></label>}
    {mode==='delegation'&&<><div className="grid sm:grid-cols-2 gap-4">{select('approverRole','Approval role',['MANAGER','FINANCE'].map(r=>({id:r,name:r})),true)}{select('teamId','Team',teams)}{select('delegateProfileId','Qualified delegate',profiles.filter(p=>p.active&&(p.role===form.approverRole||p.role==='ADMIN')).map(p=>({id:p.id,name:p.fullName||p.email})),true)}<label>From (your local time)<input required type="datetime-local" value={form.validFrom||''} onChange={e=>update('validFrom',e.target.value)}/></label><label>Until (your local time)<input required type="datetime-local" min={form.validFrom} value={form.validUntil||''} onChange={e=>update('validUntil',e.target.value)}/></label></div><label>Reason<textarea required maxLength={500} value={form.reason||''} onChange={e=>update('reason',e.target.value)}/></label></>}
    {error&&<p role="alert" className="error-notice">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}<button className="button-primary" disabled={busy}>Save configuration</button></form>
    <section className="insight-panel"><h2 className="font-semibold">Approval delegations</h2>{!delegations.length&&<p className="panel-caption">No delegations configured.</p>}{delegations.map(d=><p className="text-xs border-b py-3" key={d.id}>{d.approverRole} · {profiles.find(p=>p.id===d.delegateProfileId)?.fullName} · {formatDateTime(d.validFrom)} — {formatDateTime(d.validUntil)} · {d.reason}</p>)}</section>
  </div>;
}
