const f = (key, label, type = 'text', options, required = true) => ({ key, label, type, options, required });
export const catalogSchemas = {
  products: { label: 'Product', endpoint: '/products', fields: [f('categoryId','Category','select','categories'),f('code','Product code'),f('name','Product name'),f('description','Description','text',null,false),f('basePrice','Base price (INR)','money'),f('baseCost','Base cost (INR)','money'),f('taxRateBp','Tax (basis points; 1800 = 18%)','number'),f('fulfillmentKind','Fulfillment','select',['STOCK','NONE']),f('chargeKind','Billing type','select',['ONE_TIME','RECURRING']),f('quantityMode','Quantity','select',['INTEGER','DECIMAL']),f('promoted','Promote in recommendations','checkbox'),f('active','Active','checkbox')] },
  variants: { label: 'Variant', endpoint: '/variants', fields: [f('productId','Product','select','products'),f('sku','SKU'),f('name','Variant name'),f('priceExtra','Additional price (INR)','money'),f('cost','Override cost (INR)','money',null,false),f('weightGrams','Weight (grams)','number'),f('attributesJson','Specifications (JSON object)','text',null,false),f('substitutionGroup','Compatible group','text',null,false),f('active','Active','checkbox')] },
  prices: { label: 'Tier price', endpoint: '/price-rules', fields: [f('variantId','Variant','select','variants'),f('tier','Customer tier','select',['BRONZE','SILVER','GOLD']),f('unitPrice','Unit price (INR)','money'),f('priority','Priority','number'),f('activeFrom','Valid from','date'),f('activeUntil','Valid until','date',null,false)] },
  plans: { label: 'Subscription plan', endpoint: '/subscription-plans', fields: [f('productId','Recurring product','select','recurringProducts'),f('code','Plan code'),f('name','Plan name'),f('intervalMonths','Billing interval (months)','select',['1','3','12']),f('intervalPrice','Interval price (INR)','money'),f('intervalCost','Interval cost (INR)','money'),f('taxRateBp','Tax (basis points)','number'),f('billingAnchor','Billing anchor','select',['ACTIVATION_DATE','CALENDAR_MONTH_START']),f('prorationPolicy','Quantity change policy','select',['IMMEDIATE_PRORATED','NEXT_PERIOD']),f('cancellationPolicy','Cancellation policy','select',['END_OF_PERIOD','IMMEDIATE_PRORATED']),f('active','Active','checkbox')] },
  warehouses: { label: 'Warehouse', endpoint: '/warehouses', fields: [f('code','Warehouse code'),f('name','Warehouse name'),f('location','Location'),f('shippingFixedCost','Fixed shipping cost (INR)','money'),f('shippingCostPerKg','Shipping cost per kg (INR)','money'),f('sortOrder','Display order','number'),f('active','Active','checkbox')] },
  categories: { label: 'Category', endpoint: '/categories', createOnly: true, fields: [f('code','Category code'),f('name','Category name'),f('kind','Category kind','select',['HARDWARE','SERVICE','SUBSCRIPTION']),f('active','Active','checkbox')] },
};
