import { useState } from 'react';
import { api } from '../../services/api';

export function ReplenishmentEditor({ levels, onSaved }) {
  const [selection,setSelection]=useState(''),[values,setValues]=useState({}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  function select(i){setSelection(i);setValues(i===''?{}:{...levels[Number(i)],expectedReceiptDate:levels[Number(i)].expectedReceiptDate||'',expectedReceiptQty:''});setMessage('');setError('');}
  async function save(e){e.preventDefault();setBusy(true);setError('');try{await api.patch('/stock-levels',{variantId:values.variantId,warehouseId:values.warehouseId,reorderPoint:values.reorderPoint,targetQty:values.targetQty,expectedReceiptDate:values.expectedReceiptDate||null,expectedReceiptQty:values.expectedReceiptQty||null});setMessage('Replenishment rule saved.');await onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <details className="insight-panel"><summary className="font-semibold text-sm cursor-pointer">Replenishment thresholds & expected receipts</summary><form className="workspace-form mt-4" onSubmit={save}><label>Stock location<select required value={selection} onChange={e=>select(e.target.value)}><option value="">Select a stocked variant</option>{levels.map((l,i)=><option key={`${l.variantId}:${l.warehouseId}`} value={i}>{l.sku} · {l.warehouseCode}</option>)}</select></label>{selection!==''&&<><div className="grid sm:grid-cols-2 gap-4">{[['reorderPoint','Reorder below','number'],['targetQty','Replenish to','number'],['expectedReceiptDate','Expected receipt date','date'],['expectedReceiptQty','Expected receipt quantity','number']].map(([key,label,type])=><label key={key}>{label}<input type={type} min={type==='number'?0:undefined} step={type==='number'?'any':undefined} required={['reorderPoint','targetQty'].includes(key)} value={values[key]??''} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>)}</div><p className="panel-caption">An expected date is a planning estimate. Record a goods receipt separately when stock arrives. Leave the date blank when unconfirmed.</p><button className="button-primary" disabled={busy}>Save replenishment rule</button></>}{error&&<p role="alert" className="error-notice">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}</form></details>;
}
