import { PackageSearch, FileText, Sparkles, ShieldCheck, MessagesSquare, PackageCheck, Receipt, CircleDollarSign } from 'lucide-react';

export const stages = [
  { id: 'catalog', title: 'Build a quote', subtitle: 'Hardware + service + support', icon: PackageSearch, owner: 'Salesperson', detail: 'Select products and quantities. Customer tier prices, line discounts and recurring totals are evaluated together.', evidence: ['Customer-specific pricing', 'One-time and recurring totals', 'Live availability preview'], x: 3, y: 19 },
  { id: 'recommend', title: 'Find the right fit', subtitle: 'Cross-sell & compatible upsell', icon: Sparkles, owner: 'Salesperson + customer', detail: 'Explore useful add-ons and compatible upgrades, with explained suggestions and a preview of the price change.', evidence: ['Purchase-pattern ranking', 'Explicit compatible upgrades', 'Customer requests go to sales'], x: 27, y: 19 },
  { id: 'policy', title: 'Evaluate policy', subtitle: 'Price, discount & contribution', icon: ShieldCheck, owner: 'Policy engine', detail: 'Every saved revision is checked against tier and category ceilings, overall concessions and margin rules.', evidence: ['Server-calculated totals', 'Explainable approval reasons', 'Old approvals cannot authorize new terms'], x: 51, y: 19 },
  { id: 'review', title: 'Review exception', subtitle: 'Manager → Finance, when required', icon: FileText, owner: 'Manager + finance', detail: 'A policy exception takes the required sequential approval path. Unclear policy can be escalated to an administrator for advice.', evidence: ['Sequential decisions', 'Return with a reason', 'Auditable review history'], x: 75, y: 19 },
  { id: 'accept', title: 'Agree on the terms', subtitle: 'Negotiate → revise → accept', icon: MessagesSquare, owner: 'Customer + salesperson', detail: 'Customers discuss or counter the proposal. They accept the exact version shown; changed terms require fresh review and acceptance.', evidence: ['Private customer deal room', 'Exact-version acceptance', 'Seller adoption for counteroffers'], x: 75, y: 65 },
  { id: 'fulfill', title: 'Reserve & fulfill', subtitle: 'Warehouse split + backorders', icon: PackageCheck, owner: 'Operations', detail: 'When all gates pass, the order reserves available stock. Shortages follow the agreed backorder terms; goods receipts enable replanning.', evidence: ['Cost-aware warehouse allocation', 'No duplicate stock reservations', 'Track and dispatch real shipments'], x: 51, y: 65 },
  { id: 'bill', title: 'Invoice accurately', subtitle: 'One-time + recurring billing', icon: Receipt, owner: 'Finance', detail: 'Issue one-time invoices and recurring charges with calendar periods, quantity adjustments and cancellation credits.', evidence: ['Separate recurring schedules', 'Prorated quantity changes', 'Credits tied to original coverage'], x: 27, y: 65 },
  { id: 'paid', title: 'Record payment', subtitle: 'Receipt → allocation → balance', icon: CircleDollarSign, owner: 'Finance', detail: 'Record a received payment and allocate it to invoices. Outstanding balances and payment status come from the persisted ledger.', evidence: ['Partial and full settlement', 'Downloadable invoice documents', 'Sales, invoices and cash reported separately'], x: 3, y: 65 },
];
